name: build
on: push
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - run: make GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} prehog-verbose
  image:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: us-west-2
      - uses: aws-actions/amazon-ecr-login@v1
      - uses: docker/build-push-action@v3
        with:
          tags: 146628656107.dkr.ecr.us-west-2.amazonaws.com/gravitational/prehog:${{ github.sha }}
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1 # needed for VCS stamping
