name: helm
on:
  workflow_dispatch:
    inputs:
      chartVersion:
        description: Chart SemVer to Publish
        type: string
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: us-west-2
      - uses: aws-actions/amazon-ecr-login@v1
      - name: Package and push helm chart to Amazon ECR
        run: |
          helm package chart --app-version ${{ github.sha }} --version ${{ inputs.chartVersion }}
          helm push prehog-chart-${{ inputs.chartVersion }}.tgz oci://146628656107.dkr.ecr.us-west-2.amazonaws.com/gravitational
