name: lint
on: pull_request
permissions:
  contents: read
jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: 1.9.0
      - uses: bufbuild/buf-lint-action@v1
