{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  # Secret names are always required.
  secretName: {{ required "certificate.secretName is required to be set when certificate.enabled is true." .Values.certificate.secretName }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - goteleport
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: {{ required "certificate.dnsName is required to be set when certificate.enabled is true" .Values.certificate.dnsName }}
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - {{ required "certificate.dnsName is required to be set when certificate.enabled is true" .Values.certificate.dnsName }}
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
{{- end }}
