name: Build on Mac OS
run-name: Build on Mac OS

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  build:
    name: Build all tools on Mac OS
    runs-on: macos-12 # macos-lates is Big Sur for now

    permissions:
      contents: read

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: make build/tctl build/tsh build/tbot build/teleport